name: Aws-config Integrations

on:
  # runs on pushes to the aws branch
  push:
    branches: [aws-config]
    
  # also runs inside pull requests that target the main branch
#   pull_request:
#     branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python  
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
        
    - name: Debuging action
      run: python -c "import os; print(os.listdir())"
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip &&\
            pip install requirements.txt
            
    - name: autopep8 support
      run: |
        autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py')
    
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    
